GDQuest/website

- _src/py/get_youtube_info.py
The tool only prints the name of the playlist and the name of the video but can be easily changed
> Added youtube tool to get user playlist videos

- config.toml
> Fixed "banner" build errors.

- content/tutorial/art/pixel-art/_index.md
- content/tutorial/art/pixel-art/chapter/0_6_pixel_art_drawing_techniques.md
- content/tutorial/art/pixel-art/chapter/1_how_to_setup_krita_for_pixel_art___krita_pixel_art_tutorial.md
- content/tutorial/art/pixel-art/chapter/2_hd_index_painting_with_krita.md
- content/tutorial/art/pixel-art/chapter/3_7_tips_to_master_hd_index_painting_with_krita.md
- content/tutorial/art/pixel-art/chapter/4_how_to_draw_clouds_in_pixel_art.md
- content/tutorial/art/pixel-art/chapter/5_how_to_design_pixel_art_characters_as_in_super_time_force__part_1.md
- content/tutorial/art/pixel-art/chapter/6_how_to_draw_characters_as_in_super_time_force_–_part_2.md
- content/tutorial/art/pixel-art/chapter/_index.md
I decided to start with the pixel art series to get a feel of the
workflow with the script mentioned on #18
Regarding the script, I can already tell a few things that can be
improved:
- There's a lot of copy and paste involved, it generates the markdown
files in the same directory of the script, you then have to manually
copy/move everything to the correct place. It would be easier if the
script could do it automatically, using an option when calling it
through the cli
- The _index.md for the chapter could be created automatically when
creating the above
- Same for the _index.md of the whole series
> Please adjust the date so that the courses are more or less in the
order you can find them on the playlist page
I used the date of the first video as the series' date. If that works,
again, …
> Pixel art series added

- content/open-source/guidelines/contributing-to-gdquest-projects/index.md
- content/open-source/guidelines/kind-communication-guidelines/index.md
This PR is for discussion as well as improving the guides. Closes #84
> [WIP] Proof read & review contributing & communication guides

- content/open-source/guidelines/contributing-to-learn-godot/index.md
- content/open-source/guides/learn-godot/_index.md
- content/open-source/guides/learn-godot/beginner/index.md
- content/open-source/guides/learn-godot/developer/index.md
This is a first pass on contributors guideline to learn making games with godot. The philosophy, having quality assurance and some tech details.
Still need to do:
closes #96
> Add contributors guideline for learn-godot

- content/docs/guidelines/best-practices/godot-gdscript/index.md
Reason I didn't pushed master directly is cause I want your input :)
Closes #95
> Fix missing OpenRPG gif with YT vid

- resources/scss/_nav.scss
- resources/scss/_variables.scss
- resources/scss/modules/_buttons.scss
solves #155 
I tried to change the buttons using the provided suggestions:
and on hover:
> Improve buttons readability

- content/docs/guidelines/best-practices/godot-gdscript/_index.md
Apparently `assert` keyword now requires parentheses.  
I had to change the syntax of [one of my old project](https://github.com/crystal-bit/triple-triad-godot/commit/7ec60a00864e87beb82485b8b77803904ab93502) to run it.
PS: I searched for commit message guidelines in the REAMDE of this repo, but I couldn't find them.
> Update assert syntax

- layouts/_default/section.html
- layouts/_default/summary.html
- layouts/partials/improve-this-page.html
- layouts/partials/modules/author.html
- layouts/shortcodes/shop-call-to-action.html
- resources/scss/modules/_card.scss
Closes #152 
- [ x ] The commit message follows our guidelines.
- [ x ] You tested the changes.
- [ x ] You updated the docs or changelog.
Related issue (if applicable): # https://github.com/GDQuest/website/issues/152
Normalize card size
**Does this PR introduce a breaking change?**
Some banner doesn't fit the new ratio and some data can be hidden. That with I introduce to class è `card-sm` to prevent breaking change for the new page.
**What is the current behavior?** 
**What is the new behavior?**
**Other information**
First PR on project so feel free to give your feedback!
> normalize card size

- content/docs/guidelines/contributing-to/learn-godot/index.md
Ironically, I made a typo in the commit message :)
> fix typos in "Make Games with Godot Guides"

- content/tutorial/getting-started/learn-to/code/index.md
> Fix markdown typo in "Learn to Code" page

- config.toml
- i18n/en.toml
- i18n/es.toml
- i18n/fr.toml
- layouts/_default/baseof.html
- layouts/index.html
- layouts/partials/components/language-dropdown.html
- layouts/partials/head.html
- layouts/partials/nav-main.html
- resources/scss/_variables.scss
- resources/scss/components/language-dropdown.scss
- resources/scss/components/nav-main.scss
- resources/scss/gdquest.scss
> Multilingual support

- layouts/index.html
> Add "home_news" snippet

- i18n/ja.toml
> Add Japanese translation file

- README.md
This helps contributors make more informed decisions about features to use and fallbacks to implement.
> Document web browser support in the README

- content/docs/guidelines/best-practices/creating-demos/index.md
Minor edits for Code Demos Tutorial
> Review of code demos guide

- content/docs/guidelines/best-practices/tutorial-audiences/index.md
- Minor edits to tutorial audiences guide.
- No comments.
> Review of tutorial audiences guide

- content/docs/guidelines/best-practices/writing-good-tutorials/index.md
- update the list of learnings
- remove the leftover placeholders and comments
- improve flow, expression and grammar
> Edit the 5 habits tutorial

- content/docs/guidelines/best-practices/checklist/index.md
- content/docs/guidelines/best-practices/creating-demos/index.md
- content/docs/guidelines/best-practices/education/index.md
- content/docs/guidelines/best-practices/godot-gdscript/_index.md
- content/docs/guidelines/best-practices/tutorial-audiences/index.md
- content/docs/guidelines/best-practices/tutorial-outline/index.md
- content/docs/guidelines/best-practices/tutorial-structure/index.md
- content/docs/guidelines/best-practices/writing-good-tutorials/index.md
- content/docs/guidelines/best-practices/writing/index.md
This is a draft for the checklist for the team. @EadhCaillin could you take a look at it and tell me what you think it's missing?
Note there's only one new document, the checklist. Changes in other documents tweak the order in the site's menu, to place the checklist after the guidelines.
> Write checklist for teammates

- assets/scss/_layout.scss
- assets/scss/components/card-box.scss
- assets/scss/components/comment-form.scss
- layouts/partials/improve-this-page.html
- layouts/partials/welcomments/comment_form.html
- layouts/tutorial/single.html
Related issue (if applicable): #275
- fix cut off content on small screen #275 
- make comment form responsive
**Does this PR introduce a breaking change?**
No breaking change
**What is the current behavior?** 
Unresponsive comment form make content cut off on small screen
**What is the new behavior?**
Make comment form responsive and fix cut off
**Other information**
Add padding to `Improve this page` box
> Fix cut off content on small screen

- content/tutorial/godot/learning-paths/developer/index.md
The NotGDC-site doesn't use https but http.
Related issue (if applicable): #
No change really, just fixed a broken link in the docs.
**Does this PR introduce a breaking change?**
No
**What is the current behavior?** 
**What is the new behavior?**
**Other information**
> Fixed link to NotGDC

- content/tutorial/getting-started/learn-to/code/index.md
Related issue (if applicable): #
**Does this PR introduce a breaking change?**
**What is the current behavior?** 
CS50 URL navigates user to older version (2020)
**What is the new behavior?**
CS50 URL navigates user the latest version (2023)
**Other information**
> Update CS50 link
